config/routes.rb
Rails.application.routes.draw do
  resources :patients, only: [:index, :new, :create, :edit, :update, :destroy]
  root 'patients#index'
end

app/models/patient.rb
class Patient < ApplicationRecord

  include PgSearch

  has_one :admission, dependent: :destroy
  accepts_nested_attributes_for :admission, allow_destroy: true

  has_one :allergy, dependent: :destroy
  accepts_nested_attributes_for :allergy, allow_destroy: true

  has_one :diagnosis, through: :admission
  accepts_nested_attributes_for :diagnosis, allow_destroy: true

  has_many :medication_orders, dependent: :destroy
  accepts_nested_attributes_for :medication_orders, allow_destroy: true

  has_one :diagnostic_procedure, dependent: :destroy
  accepts_nested_attributes_for :diagnostic_procedure, allow_destroy: true

  has_one :treatment, dependent: :destroy
  accepts_nested_attributes_for :treatment, allow_destroy: true

  # Declaring enum as a Hash instead of an Array allows for easier and safer future changes.
  enum gender: { male: 0, female: 1, other: 2 },
  _prefix: :gender

  validates :gender, inclusion: { in: genders.keys }
  validates :first_name, :presence => true
  validates :last_name, :presence => true
  validates :mr, :presence => true
  validates :dob, :presence => true
  validates :gender, :presence => true


  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |patient|
        csv << patient.attributes.values_at(*column_names)
      end
    end
  end

  filterrific(
    default_filter_params: { with_date_of_gte: 1.month.ago, sorted_by: 'created_at_desc' },
    available_filters: [
      :sorted_by,
      :search_by,
      :with_date_of_gte,
      :with_date_of_lt
    ]
  )

 # always include the lower boundary for semi open intervals
 scope :with_date_of_gte, lambda { |reference_time|
   where('patients.created_at >= ?', reference_time)
 }

 # always exclude the upper boundary for semi open intervals
 scope :with_date_of_lt, lambda { |reference_time|
   where('patients.created_at <= ?', reference_time)
 }

  scope :sorted_by, lambda { |sort_option|
    # extract the sort direction from the param value.
    direction = (sort_option =~ /desc$/) ? 'desc' : 'asc'
    case sort_option.to_s
    when /^created_at_/
      # Simple sort on the created_at column.
      # Make sure to include the table name to avoid ambiguous column names.
      # Joining on other tables is quite common in Filterrific, and almost
      # every ActiveRecord table has a 'created_at' column.
      order("patients.created_at #{ direction }")
    when /^last_name_/
      # Simple sort on the name colums
      order("patients.last_name #{ direction }")
    when /^first_name_/
      # Simple sort on the name colums
      order("patients.first_name #{ direction }")
    when /^mr_/
      # Simple sort on the name colums
      order("patients.mr #{ direction }")
    when /^dob_/
      # Simple sort on the name colums
      order("patients.dob #{ direction }")
    else
      raise(ArgumentError, "Invalid sort option: #{ sort_option.inspect }")
    end
  }

  pg_search_scope :search_by, :against => [:first_name, :last_name, :middle_name, :mr, :dob]

end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController

  def index
    @filterrific = initialize_filterrific(
    Patient,
    params[:filterrific],
    select_options: {
      }
    ) or return

    @patients = @filterrific.find.page(params[:page])

    respond_to do |format|
      format.html
      format.csv { send_data @filterrific.find.to_csv }
      format.xls { send_data @filterrific.find.to_csv(col_sep: "\t") }
      format.js
    end

    rescue ActiveRecord::RecordNotFound => e
     puts "Had to reset filterrific params: #{ e.message }"
     redirect_to(reset_filterrific_url(format: :html)) and return
  end

  def new
    @patient = Patient.new
    @patient.build_allergy
    @patient.build_admission
    @medication_order = @patient.medication_orders.build
    @medication_order.build_order_frequency

    respond_to do |format|
      format.html
      format.js
    end
  end

  def create
    @patient = Patient.new(patient_params)
    binding.pry
    if @patient.save
      flash[:notice] = "Emergency Transfer Summary (Form 34L-D) for #{patient_params[:first_name]} #{patient_params[:last_name]} Has Been Created"
      redirect_to patients_path
    else
      flash.now[:alert] = "There Was An Error Creating The Transfer. Please Try Again."
      redirect_to patients_path
    end
  end

  def show
    @patient = Patient.find(params[:id])
    respond_to do |format|
      format.html
      format.js
    end
  end

  def edit
    @patient = Patient.find(params[:id])
    @patient.build_allergy
    @patient.build_admission
    @patient.build_medication_order
  end

  def update
    @patient = Patient.find(params[:id])

    @patient.assign_attributes(patient_params)

    if @patient.save
      flash[:notice] = "Transfer for #{patient_params[:first_name]} #{patient_params[:last_name]} Has Been Updated."
      redirect_to patients_path
    else
      flash.now[:alert] = "Error Updating Transfer. Please Try Again."
      redirect_to patients_path
    end
  end

  def destroy
    @patient = Patient.find(params[:id])

    if @patient.destroy
      flash[:notice] = "Transfer Was Deleted Succesfully."
      redirect_to patients_path
    end
  end

  private

  def patient_params
    params.require(:patient).permit(
      :first_name, :middle_name, :last_name, :mr, :dob, :gender,
      allergy_attributes: Allergy.attribute_names.map(&:to_sym).push(:_destroy),
      admission_attributes: Admission.attribute_names.map(&:to_sym).push(:_destroy),
      medication_orders_attributes: MedicationOrder.attribute_names.map(&:to_sym).push(:order_frequency_attributes => [:value, :unit]).push(:_destroy)
    )
  end
end

app/views/patients/_edit.html.erb
<div class="modal-body">
  <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>

  <h1 class="profile-underline">Edit Transfer for <%= @patient.first_name %> <%= @patient.last_name %></h1>
  </br>

  <%= form_for @patient do |f| %>
    <div class="field">
      <%= f.label :first_name, 'First Name:  ' %>
      <%= f.text_field :first_name, :value => @patient.first_name, :required => true, autofocus: true %>
    </div>
    </br>
    <div class="field">
      <%= f.label :middle_name, 'Middle Name:  ' %>
      <%= f.text_field :middle_name, :value => @patient.middle_name %>
    </div>
    </br>
    <div class="field">
      <%= f.label :last_name, 'Last Name:  ' %>
      <%= f.text_field :last_name, :value => @patient.last_name, :required => true %>
    </div>
    </br>
    <div class="field">
      <%= f.label :mr, 'Medical Record:  ' %>
      <%= f.text_field :mr, :value => @patient.mr, :required => true %>
    </div>
    </br>
    <div class="field ">
      <%= f.label :dob, 'Date of Birth:  ' %>
      <%= f.date_field :dob, :value => @patient.dob.to_date, :required => true %>
    </div>
    </br>
    <div class="field">
      <%= f.label :gender, 'Gender:  ' %>
      <%= f.select :gender, Patient.genders.keys.map {|gender| [gender.titleize, gender]}, :value => @patient.gender %>
    </div>
    </br>
    <div class="actions">
      <%= f.submit "Submit Transfer Edit", class: 'btn btn-success' %>
    </div>
  <% end %>
</div>

app/views/patients/_list.html.erb
<div class="fix-table">
  <div id="filterrific_results">
    <div class="text-center scroll table-content">
      <table class="table table-fixed table-bordered">
        <thead>
          <tr class='patient-list-header-font text-center'>
            <th class="text-center"><%= filterrific_sorting_link(@filterrific, :first_name, options = {label: "First Name"}) %></th>
            <th class="text-center"><%= filterrific_sorting_link(@filterrific, :last_name, options = {label: "Last Name"}) %></th>
            <th class="text-center"><%= filterrific_sorting_link(@filterrific, :dob, options = {label: "DOB"}) %></th>
            <th class="text-center"><%= filterrific_sorting_link(@filterrific, :mr, options = {label: "Medical Record"}) %></th>
            <th class="text-center"><%= filterrific_sorting_link(@filterrific, :created_at, options = {label: "Created At"}) %></th>
            <th class="text-center">Edit</th>
            <th class="text-center">Delete</th>
          </tr>
        </thead>
        <tbody>
          <% patients.each do |patient| %>
                <tr class='patient-list-font'>
                  <td class="col col-md-auto">
                    <p class="text-center"><%= link_to(patient.first_name, patient_path(patient), {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#mymodal'}) %></p>
                  </td>
                  <td class="col col-md-auto">
                    <p class="text-center"><%= link_to(patient.last_name, patient_path(patient), {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#mymodal'}) %></p>
                  </td>
                  <td class="col col-md-auto">
                    <p class="text-center"><%= patient.dob.to_date.strftime("%m-%d-%Y")  %></p>
                  </td>
                  <td class="col col-md-auto">
                    <p class="text-center"><%= patient.mr %></p>
                  </td>
                  <td class="col col-md-auto">
                    <p class="text-center"><%= patient.created_at.to_date.strftime("%m-%d-%Y") %></p>
                  </td>
                  <td class="col col-md-auto">
                    <p class="text-center"><%= link_to "Edit", edit_patient_path(patient), {:remote => true, 'data-toggle' =>  "modal", class: 'btn btn-success upgrade', style: 'margin-right: 10px', 'data-target' => '#mymodal'} %></p>
                  </td>
                  <td class="col col-md-auto">
                    <p class="text-center"><%= link_to "Delete", patient_path(patient), method: :delete, class: 'btn btn-danger user-delete', data: { confirm: 'Are you sure you want to delete this Transfer?' } %></p>
                  </td>
                </tr>
          <% end %>
        </tbody>

      </table>
    </div>
    <%= page_entries_info patients %>
    <span class="download-links">
      Download:
      <%= link_to "CSV", patients_path(format: "csv") %>
    </span>
    <%= will_paginate patients, class: 'pull-right'%>
  </div>
</div>

app/views/patients/_medication_order.html.erb
<div class="fields">
  <div class="field">
    <%= f.label :name, 'Name:  ' %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :unit, 'Unit:  ' %>
    <%= f.select :unit, MedicationOrder.mass_units.keys.map {|unit| [unit, unit]} %>
  </div>
  <div class="field">
    <%= f.label :dosage, 'Dosage:  ' %>
    <%= f.number_field :dosage, min: 0, :step => "0.01" %>
  </div>
  <div class="field">
    <%= f.label :route, 'Route:  ' %>
    <%= f.select :route, MedicationOrder.medication_routes.keys.map {|route| [route.upcase, route]} %>
  </div>
  <%= f.fields_for :order_frequency do |f| %>
    <div class="field">
      <%= f.label :value, 'Frequency:  ' %>
      <%= f.text_field :value %>
      <%= f.select :unit, OrderFrequency.frequency_units.map {|frequency| [frequency, frequency]} %>
    </div>
  <% end %>
  <%= link_to_remove_fields "Remove", f %>
</div>

app/views/patients/_new.html.erb
<div class="modal-body">
  <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>

  <h3 class="profile-underline">New Emergency Transfer Summary (Form 34L-D)</h3>
  </br>

  <h3>Patient:</h3>

  <%= form_for @patient do |f| %>
    <div class="field">
      <%= f.label :first_name, 'First Name:  ' %>
      <%= f.text_field :first_name, :required => true, autofocus: true %>
    </div>
    </br>
    <div class="field">
      <%= f.label :middle_name, 'Middle Name:  ' %>
      <%= f.text_field :middle_name %>
    </div>
    </br>
    <div class="field">
      <%= f.label :last_name, 'Last Name:  ' %>
      <%= f.text_field :last_name, :required => true %>
    </div>
    </br>
    <div class="field">
      <%= f.label :mr, 'Medical Record:  ' %>
      <%= f.text_field :mr, :required => true %>
    </div>
    </br>
    <div class="field ">
      <%= f.label :dob, 'Date of Birth:  ' %>
      <%= f.date_field :dob, :required => true %>
    </div>
    </br>
    <div class="field">
      <%= f.label :gender, 'Gender:  ' %>
      <%= f.select :gender, Patient.genders.keys.map {|gender| [gender.titleize, gender]} %>
    </div>
    </br>
    <%= f.fields_for :allergy do |f| %>
      <div class="field">
        <%= f.label :description, 'Allergies:  ' %>
        <%= f.text_area :description %>
      </div>
      </br>
    <% end %>
    <h3>Admission:</h3>
    <%= f.fields_for :admission do |f| %>
      <div class="field">
        <%= f.label :moment, 'Date/Time:  ' %>
        <%= f.datetime_select :moment, {order: [:day, :month, :year, :hour, :minute]} %>
      </div>
      </br>
    <% end %>

  <!-- Medications -->
    <h3>Medications:</h3>
    <%= f.fields_for :medication_orders do |builder| %>
      <%= render 'patients/medication_order', f: builder %>
    <% end %>

    <div class="form-actions">
      <%= link_to_add_fields "Add Medication", f, :medication_orders, class: 'btn btn-primary' %>
    </div>

    <div class="actions">
      <%= f.submit "Submit Transfer Summary", class: 'btn btn-success' %>
    </div>
  <% end %>
</div>

app/views/patients/_show.html.erb
<div class="modal-body">
  <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>

    <h1>Food Born Illness</h1>
    <p>Name: <%= @fbi.name %> </p>
    <p>Email: <%= @fbi.email %></p>
    <p>Manager on Duty: <%= @fbi.manager %></p>
    <p>Guest Name: <%= @fbi.guest_name %></p>
    <p>Guest Phone Number: <%= @fbi.guest_phone %></p>
    <p>Guest Address: <%= @fbi.guest_address %></p>
    <p>Guest Email: <%= @fbi.guest_email %></p>
    <p>Date of Incedent: <%= @fbi.date_of.strftime("%m/%d/%Y") %></p>
    <p>Time of Incedent: <%= @fbi.time_of %></p>
    <p>Estimated Date/Time of Food Born Illness: <%= @fbi.time_of_illness %></p>
    <p>Foods Consumed: <%= @fbi.foods_eaten %></p>
    <p>Beverages Consumed: <%= @fbi.beverage_eaten %></p>
    <% if @fbi.all_items_consumed == true %>
      <p>Were All Types of Ordered Food Consumed: Yes</p>
    <% else %>
      <p>Were All Types of Ordered Food Consumed: No</p>
    <% end %>
    <p>Time after eating they became sick: <%= @fbi.time_after %></p>
    <p>What symptoms did they have: <%= @fbi.symptoms %></p>
    <p>How long did the symptoms last: <%= @fbi.length_of_symptoms %></p>
    <% if @fbi.medical_attention == true %>
      <p>Did the Complainant Seek Medical Attention: Yes</p>
    <% else %>
      <p>Did the Complainant Seek Medical Attention: No</p>
    <% end %>
    <p>When did they seek medical attention: <%= @fbi.medical_when %></p>
    <p>Name of Doctor/Facility Where Treated: <%= @fbi.doctor %></p>
    <% if @fbi.tested_for_fbi == true %>
      <p>Were They Tested for Food Borne Illness: Yes</p>
    <% else %>
      <p>Were They Tested for Food Borne Illness: No</p>
    <% end %>
    <% if @fbi.medical_report == true %>
      <p>Do They Have a Medical Report: Yes</p>
    <% else %>
      <p>Do They Have a Medical Report: No</p>
    <% end %>
    <p>Action Taken: <%= @fbi.action_taken %></p>
    <p>Main Item Type Consumed (Item Thought to be the cause): <%= @fbi.suspected_cause %></p>
    <p>Dine: <%= @fbi.dine %></p>
    <p>Give any comp dollars: <%= @fbi.comp_dollars %></p>
    <p>Give any corp bucks: <%= @fbi.corp_bucks %></p>
    <p>Location: <%= @fbi.location %></p>
    <p>Menu Item: <%= @fbi.menu_item %></p>
    <p>Description: <%= @fbi.description %></p>
</div>

app/views/patients/edit.js.erb
$("#mymodal").find(".modal-content").html("<%= j render(partial: 'patients/edit') %>");

app/views/patients/index.html.erb
<div class="container">
  <div class='patient-list'>
    <div class="navbar navbar-default">
  <%= form_for_filterrific @filterrific do |f| %>
  <ul class="nav navbar-nav search-form">
    <%= link_to "New Transfer", new_patient_path, {:remote => true, 'data-toggle' =>  "modal", class: 'btn btn-success upgrade', style: 'margin-right: 10px', 'data-target' => '#mymodal'} %>

  <li>
  Search
  <%= f.text_field(
    :search_by,
    class: 'filterrific-periodically-observed'
  ) %>
  </li>

  <li>
    From:
    <%= f.date_field(:with_date_of_gte, :value => 1.month.ago.strftime("%Y-%m-%d")) %>&nbsp;&nbsp;
  </li>
  <li>
    To:
    <%= f.date_field(:with_date_of_lt) %>&nbsp;&nbsp;
  </li>

  <li>
  <%= link_to(
    'Reset filters',
    reset_filterrific_url,
  ) %>
  </li>
  <%= render_filterrific_spinner %>
  <% end %>
  </ul>
  </div>
    <div>
      <%= render(
        partial: 'patients/list',
        locals: { patients: @patients }
      ) %>
    </div>
  </div>
</div>

app/views/patients/index.js.erb
$("#filterrific_results").html("<%= j render(partial: 'patients/list', locals: { patients: @patients }) %>");

app/views/patients/new.js.erb
$("#mymodal").find(".modal-content").html("<%= j render(partial: 'patients/new') %>");
function remove_fields(link) {
  $(link).prev("input[type=hidden]").val("1");
  $(link).closest(".fields").hide();
};

function add_fields(link, association, content) {
  var new_id = new Date().getTime();
  var regexp = new RegExp("new_" + association, "g")
  $(link).parent().before(content.replace(regexp, new_id));
};

app/views/patients/show.js.erb
$("#mymodal").find(".modal-content").html("<%= j render(partial: 'patients/show') %>");